---
- name: Install httpd Package
  yum: name=httpd state=latest

- name: Install mod_ssl configuration file
  template:
    src: files/ssl.conf.j2
    dest: "{{ httpd_ssl_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: Install index.html
  template:
    src: files/index.html.j2
    dest: /var/www/html/index.html
    mode: 0777
  notify: restart httpd
  
- name: Add PHP 7 PPA Repo
    become: true
    apt_repository:
     repo: 'ppa:ondrej/php'

- name: install git, apache and moodle dependencies
    apt:
     name: "{{ packages }}"
    vars:
     packages:
     - php7.2-curl
     - php7.2-gd
     - php7.2-intl
     - php7.2-mysql
     - php7.2-xml
     - php7.2-xmlrpc
     - php7.2-ldap
     - php7.2-zip
     - php7.2-soap
     - php7.2-mbstring
     - php7.2-pspell
     - php7.2-cli